; Минимум для демо: софтфон клиента 1001 и софтфон оператора operator
[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[1001]
type=endpoint
context=saqta-inbound
disallow=all
allow=ulaw,alaw
auth=1001
aors=1001
callerid="Demo client" <+77010000007>
[1001]
type=auth
auth_type=userpass
username=1001
password=change-me
[1001]
type=aor
max_contacts=1

[operator]
type=endpoint
context=saqta-inbound
disallow=all
allow=ulaw,alaw
auth=operator
aors=operator
[operator]
type=auth
auth_type=userpass
username=operator
password=change-me
[operator]
type=aor
max_contacts=1
